### YamlMime:ManagedReference
items:
- uid: Repetitionless.Samples.TerrainSceneSettings
  commentId: T:Repetitionless.Samples.TerrainSceneSettings
  id: TerrainSceneSettings
  parent: Repetitionless.Samples
  children:
  - Repetitionless.Samples.TerrainSceneSettings.TerrainUsingRepetitionless
  - Repetitionless.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless
  langs:
  - csharp
  - vb
  name: TerrainSceneSettings
  nameWithType: TerrainSceneSettings
  fullName: Repetitionless.Samples.TerrainSceneSettings
  type: Class
  source:
    remote:
      path: True Seamless Texturing/Assets/Repetitionless/Samples/Assets/Scripts/Runtime/TerrainSceneSettings.cs
      branch: main
      repo: https://github.com/WilliamSchack/True-Seamless-Texturing.git
    id: TerrainSceneSettings
    path: ../Assets/Repetitionless/Samples/Assets/Scripts/Runtime/TerrainSceneSettings.cs
    startLine: 8
  assemblies:
  - com.williamschack.Repetitionless
  namespace: Repetitionless.Samples
  syntax:
    content: 'public class TerrainSceneSettings : MonoBehaviour'
    content.vb: Public Class TerrainSceneSettings Inherits MonoBehaviour
  inheritance:
  - System.Object
  - UnityEngine.Object
  - UnityEngine.Component
  - UnityEngine.Behaviour
  - UnityEngine.MonoBehaviour
- uid: Repetitionless.Samples.TerrainSceneSettings.TerrainUsingRepetitionless
  commentId: F:Repetitionless.Samples.TerrainSceneSettings.TerrainUsingRepetitionless
  id: TerrainUsingRepetitionless
  parent: Repetitionless.Samples.TerrainSceneSettings
  langs:
  - csharp
  - vb
  name: TerrainUsingRepetitionless
  nameWithType: TerrainSceneSettings.TerrainUsingRepetitionless
  fullName: Repetitionless.Samples.TerrainSceneSettings.TerrainUsingRepetitionless
  type: Field
  source:
    remote:
      path: True Seamless Texturing/Assets/Repetitionless/Samples/Assets/Scripts/Runtime/TerrainSceneSettings.cs
      branch: main
      repo: https://github.com/WilliamSchack/True-Seamless-Texturing.git
    id: TerrainUsingRepetitionless
    path: ../Assets/Repetitionless/Samples/Assets/Scripts/Runtime/TerrainSceneSettings.cs
    startLine: 15
  assemblies:
  - com.williamschack.Repetitionless
  namespace: Repetitionless.Samples
  syntax:
    content: >-
      [HideInInspector]

      public bool TerrainUsingRepetitionless
    return:
      type: System.Boolean
    content.vb: >-
      <HideInInspector>

      Public TerrainUsingRepetitionless As Boolean
  attributes:
  - type: UnityEngine.HideInInspector
    ctor: UnityEngine.HideInInspector.#ctor
    arguments: []
- uid: Repetitionless.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless
  commentId: M:Repetitionless.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless
  id: ToggleTerrainRepetitionless
  parent: Repetitionless.Samples.TerrainSceneSettings
  langs:
  - csharp
  - vb
  name: ToggleTerrainRepetitionless()
  nameWithType: TerrainSceneSettings.ToggleTerrainRepetitionless()
  fullName: Repetitionless.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless()
  type: Method
  source:
    remote:
      path: True Seamless Texturing/Assets/Repetitionless/Samples/Assets/Scripts/Runtime/TerrainSceneSettings.cs
      branch: main
      repo: https://github.com/WilliamSchack/True-Seamless-Texturing.git
    id: ToggleTerrainRepetitionless
    path: ../Assets/Repetitionless/Samples/Assets/Scripts/Runtime/TerrainSceneSettings.cs
    startLine: 17
  assemblies:
  - com.williamschack.Repetitionless
  namespace: Repetitionless.Samples
  syntax:
    content: public void ToggleTerrainRepetitionless()
    content.vb: Public Sub ToggleTerrainRepetitionless()
  overload: Repetitionless.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless*
references:
- uid: Repetitionless.Samples
  commentId: N:Repetitionless.Samples
  name: Repetitionless.Samples
  nameWithType: Repetitionless.Samples
  fullName: Repetitionless.Samples
  spec.csharp:
  - uid: Repetitionless
    name: Repetitionless
  - name: .
  - uid: Repetitionless.Samples
    name: Samples
  spec.vb:
  - uid: Repetitionless
    name: Repetitionless
  - name: .
  - uid: Repetitionless.Samples
    name: Samples
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: UnityEngine.Object
  commentId: T:UnityEngine.Object
  parent: UnityEngine
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: UnityEngine.Object
- uid: UnityEngine.Component
  commentId: T:UnityEngine.Component
  parent: UnityEngine
  isExternal: true
  name: Component
  nameWithType: Component
  fullName: UnityEngine.Component
- uid: UnityEngine.Behaviour
  commentId: T:UnityEngine.Behaviour
  parent: UnityEngine
  isExternal: true
  name: Behaviour
  nameWithType: Behaviour
  fullName: UnityEngine.Behaviour
- uid: UnityEngine.MonoBehaviour
  commentId: T:UnityEngine.MonoBehaviour
  parent: UnityEngine
  isExternal: true
  name: MonoBehaviour
  nameWithType: MonoBehaviour
  fullName: UnityEngine.MonoBehaviour
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Repetitionless.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless*
  commentId: Overload:Repetitionless.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless
  name: ToggleTerrainRepetitionless
  nameWithType: TerrainSceneSettings.ToggleTerrainRepetitionless
  fullName: Repetitionless.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless
