#ifndef REPETITIONLESSPRAGMASLITKEYWORDS_INCLUDED
#define REPETITIONLESSPRAGMASLITKEYWORDS_INCLUDED

#pragma shader_feature_local _ _REPETITIONLESS_DISTANCE_BLEND
#pragma shader_feature_local _ _REPETITIONLESS_MATERIAL_BLEND
#pragma shader_feature_local _ _REPETITIONLESS_TRIPLANAR
#pragma shader_feature_local _ _REPETITIONLESS_NOISE_TEXTURE
#pragma shader_feature_local _ _REPETITIONLESS_VARIATION

#pragma shader_feature_local_fragment _ _SPECULARHIGHLIGHTS_OFF
#pragma shader_feature_local_fragment _ _ENVIRONMENTREFLECTIONS_OFF

#endif