site_name: Repetitionless
#site_url: https://docs.wilschack.dev/texture-urray-utilities
nav:
  - Introduction: index.md
  - Installation: installation.md
  - Samples: samples.md
  - Getting Started: getting-started.md
  - Shader Creation: shader-creation.md
  - Scripting: scripting.md
  - Submitting Issues: issues.md
  - Sub Graphs:
    - Compression:
      - Add Compressed Bool: SubGraphs/BooleanCompression.AddCompressedBool.md
      - Get Compressed Bool: SubGraphs/BooleanCompression.GetCompressedBool.md
    - Distance Blending:
      - Distance Blend Colour: SubGraphs/DistanceBlend.DistanceBlendColour.md
      - Distance Blend Texture: SubGraphs/DistanceBlend.DistanceBlendTexture.md
      - Distance Blend Tiling Offset: SubGraphs/DistanceBlend.DistanceBlendTilingOffset.md
    - Macro Micro Variation:
      - MMV Perlin Noise: SubGraphs/MacroMicroVariation.MMVPerlinNoise.md
      - MMV Simplex Noise: SubGraphs/MacroMicroVariation.MMVSimplexNoise.md
      - MMV Texture: SubGraphs/MacroMicroVariation.MMVTexture.md
    - Noise:
      - Repetitionless Noise: SubGraphs/Noise.RepetitionlessNoise.md
    - Internal:
      - Add Terrain Layer Mask Settings: SubGraphs/Terrain.AddTerrainLayerMaskSettings.md
  - Shader API:
    - Main:
      - SampleRepetitionlessMaterial: ShaderHLSL/Main.SampleRepetitionlessMaterial.md
      - SampleRepetitionlessLayer: ShaderHLSL/Main.SampleRepetitionlessLayer.md
    - Noise:
      - VoronoiNoise2D: ShaderHLSL/Noise.VoronoiNoise2D.md
      - Keijiro:
        - ClassicNoise2D: ShaderHLSL/Noise.Keijiro.ClassicNoise2D.md
        - SimplexNoise2D: ShaderHLSL/Noise.Keijiro.SimplexNoise2D.md
    - RepetitionlessHelpers:
      - DistanceBlend: ShaderHLSL/RepetitionlessHelpers.DistanceBlend.md
      - MacroMicroVariation: ShaderHLSL/RepetitionlessHelpers.MacroMicroVariation.md
      - RepetitionlessNoise: ShaderHLSL/RepetitionlessHelpers.RepetitionlessNoise.md
      - RepetitionlessTextureUtilities: ShaderHLSL/RepetitionlessHelpers.RepetitionlessTextureUtilities.md
    - Utilities: 
      - BooleanCompression: ShaderHLSL/Utilities.BooleanCompression.md
      - TextureUtilities: ShaderHLSL/Utilities.TextureUtilities.md
    - Structs: 
      - RepetitionlessLayer: ShaderHLSL/Structs.RepetitionlessLayer.md
      - RepetitionlessLayerTerrain: ShaderHLSL/Structs.RepetitionlessLayerTerrain.md
      - RepetitionlessLayerData: ShaderHLSL/Structs.RepetitionlessLayerData.md
      - RepetitionlessMaterial: ShaderHLSL/Structs.RepetitionlessMaterial.md
      - RepetitionlessMaterialArray: ShaderHLSL/Structs.RepetitionlessMaterialArray.md
      - RepetitionlessMaterialData: ShaderHLSL/Structs.RepetitionlessMaterialData.md
    - TextureArrayEssentials:
      - TextureArrayUtilities: ShaderHLSL/TextureArrayEssentials.TextureArrayUtilities.md
  - Scripting API:
    - Compression:
      - BooleanCompression: Scripting/Repetitionless.Compression.BooleanCompression.md
    - CustomDialog:
      - ShaderGUIDialog: Scripting/Repetitionless.CustomDialog.ShaderGUIDialog.md
    - CustomWindows:
      - Texture2DArrayWindowBase: Scripting/Repetitionless.CustomWindows.Texture2DArrayWindowBase.md
    - GUIUtilities:
      - TextureArrayGUIDrawer: Scripting/Repetitionless.GUIUtilities.TextureArrayGUIDrawer.md
      - GUIUtilities: Scripting/Repetitionless.GUIUtilities.GUIUtilities.md
    - Inspectors:
      - RepetitionlessGUIBase: Scripting/Repetitionless.Inspectors.RepetitionlessGUIBase.md
      - Variables:
        - MaterialFoldoutState: Scripting/Repetitionless.Inspectors.RepetitionlessGUIBase.MaterialFoldoutState.md
    - TextureUtilities:
      - Texture2DArrayUtilities: Scripting/Repetitionless.TextureUtilities.Texture2DArrayUtilities.md
      - TextureUtilities: Scripting/Repetitionless.TextureUtilities.TextureUtilities.md
    - Variables:
      - EDistanceBlendMode: Scripting/Repetitionless.Variables.EDistanceBlendMode.md
      - ESurfaceType: Scripting/Repetitionless.Variables.ESurfaceType.md
      - ETextureType: Scripting/Repetitionless.Variables.ETextureType.md
theme:
    name: material
    logo: Images/Icon.png
    favicon: Images/Icon_Favicon.png
    features:
      - navigation.instant
      - navigation.instant.progress
      - search.suggest
      - search.highlight
      - content.code.copy
    palette:
        # Palette toggle for light mode
      - scheme: default
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
    
        # Palette toggle for dark mode
      - scheme: slate
        toggle:
            icon: material/brightness-4
            name: Switch to light mode
markdown_extensions:
  - toc:
      toc_depth: 2
  - pymdownx.superfences
plugins:
  - search
# Remove comments on all below when building as pdf
#  - with-pdf:
#        author: William Schack
#        copyright: (C) 2025 William Schack
#        cover: true
#        cover_title: Texture Array Essentials
#        cover_subtitle: The offline documentation can be hard to follow so using the online documentation is recommended which you can find at https://docs.wilschack.dev/texture-array-essentials. You can still use this if you need though, it has all the same information
#        toc_level: 2
#extra_css:
#  - pdf-style.css
