site_name: Repetitionless
#site_url: https://docs.wilschack.dev/repetitionless
nav:
  - Introduction: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Samples: samples.md
  - Using Regular Materials: material-regular.md
  - Using Terrain Materials: material-terrain.md
  - Material Properties: material-properties.md
  - Shader Creation: shader-creation.md
  - Scripting: scripting.md
  - Submitting Issues: issues.md
  - Sub Graphs:
    - Compression:
      - Add Compressed Bool: SubGraphs/BooleanCompression.AddCompressedBool.md
      - Get Compressed Bool: SubGraphs/BooleanCompression.GetCompressedBool.md
    - Distance Blending:
      - Distance Blend Colour: SubGraphs/DistanceBlend.DistanceBlendColour.md
      - Distance Blend Texture: SubGraphs/DistanceBlend.DistanceBlendTexture.md
      - Distance Blend Tiling Offset: SubGraphs/DistanceBlend.DistanceBlendTilingOffset.md
    - Macro Micro Variation:
      - MMV Perlin Noise: SubGraphs/MacroMicroVariation.MMVPerlinNoise.md
      - MMV Simplex Noise: SubGraphs/MacroMicroVariation.MMVSimplexNoise.md
      - MMV Texture: SubGraphs/MacroMicroVariation.MMVTexture.md
    - Noise:
      - Repetitionless Noise: SubGraphs/Noise.RepetitionlessNoise.md
    - Internal:
      - Add Terrain Layer Mask Settings: SubGraphs/Terrain.AddTerrainLayerMaskSettings.md
  - Shader API:
    - Main:
      - SampleRepetitionlessMaterial: ShaderHLSL/Main.SampleRepetitionlessMaterial.md
      - SampleRepetitionlessLayer: ShaderHLSL/Main.SampleRepetitionlessLayer.md
      - SampleRepetitionlessTerrain: ShaderHLSL/Main.SampleRepetitionlessTerrain.md
    - Noise:
      - VoronoiNoise2D: ShaderHLSL/Noise.VoronoiNoise2D.md
      - Keijiro:
        - ClassicNoise2D: ShaderHLSL/Noise.Keijiro.ClassicNoise2D.md
        - SimplexNoise2D: ShaderHLSL/Noise.Keijiro.SimplexNoise2D.md
    - RepetitionlessHelpers:
      - DistanceBlend: ShaderHLSL/RepetitionlessHelpers.DistanceBlend.md
      - MacroMicroVariation: ShaderHLSL/RepetitionlessHelpers.MacroMicroVariation.md
      - RepetitionlessNoise: ShaderHLSL/RepetitionlessHelpers.RepetitionlessNoise.md
      - RepetitionlessTextureUtilities: ShaderHLSL/RepetitionlessHelpers.RepetitionlessTextureUtilities.md
      - GetArrayAssignedTextures: ShaderHLSL/RepetitionlessHelpers.GetArrayAssignedTextures.md
    - Utilities: 
      - BooleanCompression: ShaderHLSL/Utilities.BooleanCompression.md
      - TextureUtilities: ShaderHLSL/Utilities.TextureUtilities.md
    - Structs: 
      - RepetitionlessMaterialData: ShaderHLSL/Structs.RepetitionlessMaterialData.md
    - TextureArrayEssentials:
      - TextureArrayUtilities: ShaderHLSL/TextureArrayEssentials.TextureArrayUtilities.md
  - Scripting API:
    - Runtime:
      - RepetitionlessTerrain: Scripting/Repetitionless.RepetitionlessTerrain.md
      - Compression:
        - BooleanCompression: Scripting/Repetitionless.Compression.BooleanCompression.md
      - Variables:
        - EDistanceBlendMode: Scripting/Repetitionless.Variables.EDistanceBlendMode.md
        - ESurfaceType: Scripting/Repetitionless.Variables.ESurfaceType.md
        - ETextureType: Scripting/Repetitionless.Variables.ETextureType.md
        - EUVSpace: Scripting/Repetitionless.Variables.EUVSpace.md
        - RepetitionlessMaterialData: Scripting/Repetitionless.Variables.RepetitionlessMaterialData.md
        - RepetitionlessMaterialDataCompressed: Scripting/Repetitionless.Variables.RepetitionlessMaterialDataCompressed.md
        - RepetitionlessLayerData: Scripting/Repetitionless.Variables.RepetitionlessLayerData.md
        - RepetitionlessLayerDataCompressed: Scripting/Repetitionless.Variables.RepetitionlessLayerDataCompressed.md
        - SerializableDictionary: Scripting/Repetitionless.Variables.SerializableDictionary-2.md
    - Editor:
      - Data:
        - MaterialDataManager: Scripting/Repetitionless.Editor.Data.MaterialDataManager.md
        - RepetitionlessMaterialDataSO: Scripting/Repetitionless.Editor.Data.RepetitionlessMaterialDataSO.md
        - RepetitionlessTextureDataSO: Scripting/Repetitionless.Editor.Data.RepetitionlessTextureDataSO.md
        - RepetitionlessTextureDataSO Variables:
          - MaterialTextureData: Scripting/Repetitionless.Editor.Data.RepetitionlessTextureDataSO.MaterialTextureData.md
          - LayerTextureData: Scripting/Repetitionless.Editor.Data.RepetitionlessTextureDataSO.LayerTextureData.md
        - TerrainLayerSyncDataSO: Scripting/Repetitionless.Editor.Data.TerrainLayerSyncDataSO.md
        - TerrainLayerSyncDataSO Variables:
          - TerrainLayerList: Scripting/Repetitionless.Editor.Data.TerrainLayerSyncDataSO.TerrainLayerList.md
          - MaterialList: Scripting/Repetitionless.Editor.Data.TerrainLayerSyncDataSO.MaterialList.md
        - RepetitionlessDataPacker: Scripting/Repetitionless.Editor.Data.RepetitionlessDataPacker.md
      - GUIUtilities:
        - GUIUtilities: Scripting/Repetitionless.Editor.GUIUtilities.GUIUtilities.md
        - TextureArrayCustomChannelsGUIDrawer: Scripting/Repetitionless.Editor.GUIUtilities.TextureArrayCustomChannelsGUIDrawer.md
      - Inspectors:
        - RepetitionlessTerrainEditor: Scripting/Repetitionless.Editor.Inspectors.RepetitionlessTerrainEditor.md
        - RepetitionlessMaterialEditorMaster: Scripting/Repetitionless.Editor.Inspectors.RepetitionlessMaterialEditorMaster.md
        - RepetitionlessMaterialEditorTerrain: Scripting/Repetitionless.Editor.Inspectors.RepetitionlessMaterialEditorTerrain.md
        - RepetitionlessMaterialEditorBase: Scripting/Repetitionless.Editor.Inspectors.RepetitionlessMaterialEditorBase.md
        - RepetitionlessMaterialEditorBase Variables:
          - MaterialFoldoutState: Scripting/Repetitionless.Editor.Inspectors.RepetitionlessMaterialEditorBase.MaterialFoldoutState.md
          - TextureDrawerDetails: Scripting/Repetitionless.Editor.Inspectors.RepetitionlessMaterialEditorBase.TextureDrawerDetails.md
      - TextureUtilities:
        - TexturePacker: Scripting/Repetitionless.Editor.TextureUtilities.TexturePacker.md
        - TexturePacker Variables:
          - TextureData: Scripting/Repetitionless.Editor.TextureUtilities.TexturePacker.TextureData.md
          - TextureChannel: Scripting/Repetitionless.Editor.TextureUtilities.TexturePacker.TextureChannel.md
          - FromToChannel: Scripting/Repetitionless.Editor.TextureUtilities.TexturePacker.FromToChannel.md
        - TextureUtilities: Scripting/Repetitionless.Editor.TextureUtilities.TextureUtilities.md
        - Texture2DArrayUtilities: Scripting/Repetitionless.Editor.TextureUtilities.Texture2DArrayUtilities.md
      - CustomDialog:
        - ShaderGUIDialog: Scripting/Repetitionless.Editor.CustomDialog.ShaderGUIDialog.md
      - CustomWindows:
        - Texture2DArrayWindowBase: Scripting/Repetitionless.Editor.CustomWindows.Texture2DArrayWindowBase.md
      - Processors:
        - RepetitionlessColourSpaceUpdater: Scripting/Repetitionless.Editor.Processors.RepetitionlessColourSpaceUpdater.md
theme:
    name: material
    logo: Images/Icon.png
    favicon: Images/Icon_Favicon.png
    features:
      - navigation.instant
      - navigation.instant.progress
      - search.suggest
      - search.highlight
      - content.code.copy
    palette:
        # Palette toggle for light mode
      - scheme: default
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
    
        # Palette toggle for dark mode
      - scheme: slate
        toggle:
            icon: material/brightness-4
            name: Switch to light mode
markdown_extensions:
  - toc:
      toc_depth: 2
  - pymdownx.superfences
plugins:
  - search
# Remove comments on all below when building as pdf
  - with-pdf:
        author: William Schack
        copyright: (C) 2025 William Schack
        cover: true
        cover_title: Repetitionless
        cover_subtitle: The offline documentation can be hard to follow so using the online documentation is recommended which you can find at https://docs.wilschack.dev/repetitionless. You can still use this if you need though, it has all the same information
        toc_level: 2
extra_css:
  - pdf-style.css
