### YamlMime:ManagedReference
items:
- uid: Repetitionless.Editor.Samples.TerrainSceneSettingsEditor
  commentId: T:Repetitionless.Editor.Samples.TerrainSceneSettingsEditor
  id: TerrainSceneSettingsEditor
  parent: Repetitionless.Editor.Samples
  children:
  - Repetitionless.Editor.Samples.TerrainSceneSettingsEditor.OnInspectorGUI
  langs:
  - csharp
  - vb
  name: TerrainSceneSettingsEditor
  nameWithType: TerrainSceneSettingsEditor
  fullName: Repetitionless.Editor.Samples.TerrainSceneSettingsEditor
  type: Class
  source:
    remote:
      path: True Seamless Texturing/Assets/Samples/Repetitionless/1.0.0/Core Sample Assets/Scripts/Editor/TerrainSceneSettingsEditor.cs
      branch: main
      repo: https://github.com/WilliamSchack/True-Seamless-Texturing.git
    id: TerrainSceneSettingsEditor
    path: ../../True Seamless Texturing/Assets/Samples/Repetitionless/1.0.0/Core Sample Assets/Scripts/Editor/TerrainSceneSettingsEditor.cs
    startLine: 8
  assemblies:
  - com.williamschack.Repetitionless.Editor.Samples
  namespace: Repetitionless.Editor.Samples
  syntax:
    content: >-
      [CustomEditor(typeof(TerrainSceneSettings))]

      public class TerrainSceneSettingsEditor : Editor
    content.vb: >-
      <CustomEditor(GetType(TerrainSceneSettings))>

      Public Class TerrainSceneSettingsEditor Inherits Editor
  inheritance:
  - System.Object
  - UnityEngine.Object
  - UnityEngine.ScriptableObject
  - UnityEditor.Editor
  attributes:
  - type: UnityEditor.CustomEditor
    ctor: UnityEditor.CustomEditor.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: {}
- uid: Repetitionless.Editor.Samples.TerrainSceneSettingsEditor.OnInspectorGUI
  commentId: M:Repetitionless.Editor.Samples.TerrainSceneSettingsEditor.OnInspectorGUI
  id: OnInspectorGUI
  parent: Repetitionless.Editor.Samples.TerrainSceneSettingsEditor
  langs:
  - csharp
  - vb
  name: OnInspectorGUI()
  nameWithType: TerrainSceneSettingsEditor.OnInspectorGUI()
  fullName: Repetitionless.Editor.Samples.TerrainSceneSettingsEditor.OnInspectorGUI()
  type: Method
  source:
    remote:
      path: True Seamless Texturing/Assets/Samples/Repetitionless/1.0.0/Core Sample Assets/Scripts/Editor/TerrainSceneSettingsEditor.cs
      branch: main
      repo: https://github.com/WilliamSchack/True-Seamless-Texturing.git
    id: OnInspectorGUI
    path: ../../True Seamless Texturing/Assets/Samples/Repetitionless/1.0.0/Core Sample Assets/Scripts/Editor/TerrainSceneSettingsEditor.cs
    startLine: 30
  assemblies:
  - com.williamschack.Repetitionless.Editor.Samples
  namespace: Repetitionless.Editor.Samples
  syntax:
    content: public override void OnInspectorGUI()
    content.vb: Public Overrides Sub OnInspectorGUI()
  overridden: UnityEditor.Editor.OnInspectorGUI
  overload: Repetitionless.Editor.Samples.TerrainSceneSettingsEditor.OnInspectorGUI*
references:
- uid: Repetitionless.Editor.Samples
  commentId: N:Repetitionless.Editor.Samples
  name: Repetitionless.Editor.Samples
  nameWithType: Repetitionless.Editor.Samples
  fullName: Repetitionless.Editor.Samples
  spec.csharp:
  - uid: Repetitionless
    name: Repetitionless
  - name: .
  - uid: Repetitionless.Editor
    name: Editor
  - name: .
  - uid: Repetitionless.Editor.Samples
    name: Samples
  spec.vb:
  - uid: Repetitionless
    name: Repetitionless
  - name: .
  - uid: Repetitionless.Editor
    name: Editor
  - name: .
  - uid: Repetitionless.Editor.Samples
    name: Samples
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: UnityEngine.Object
  commentId: T:UnityEngine.Object
  parent: UnityEngine
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: UnityEngine.Object
- uid: UnityEngine.ScriptableObject
  commentId: T:UnityEngine.ScriptableObject
  parent: UnityEngine
  isExternal: true
  name: ScriptableObject
  nameWithType: ScriptableObject
  fullName: UnityEngine.ScriptableObject
- uid: UnityEditor.Editor
  commentId: T:UnityEditor.Editor
  parent: UnityEditor
  isExternal: true
  name: Editor
  nameWithType: Editor
  fullName: UnityEditor.Editor
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: UnityEditor
  commentId: N:UnityEditor
  isExternal: true
  name: UnityEditor
  nameWithType: UnityEditor
  fullName: UnityEditor
- uid: UnityEditor.Editor.OnInspectorGUI
  commentId: M:UnityEditor.Editor.OnInspectorGUI
  parent: UnityEditor.Editor
  isExternal: true
  name: OnInspectorGUI()
  nameWithType: Editor.OnInspectorGUI()
  fullName: UnityEditor.Editor.OnInspectorGUI()
  spec.csharp:
  - uid: UnityEditor.Editor.OnInspectorGUI
    name: OnInspectorGUI
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: UnityEditor.Editor.OnInspectorGUI
    name: OnInspectorGUI
    isExternal: true
  - name: (
  - name: )
- uid: Repetitionless.Editor.Samples.TerrainSceneSettingsEditor.OnInspectorGUI*
  commentId: Overload:Repetitionless.Editor.Samples.TerrainSceneSettingsEditor.OnInspectorGUI
  name: OnInspectorGUI
  nameWithType: TerrainSceneSettingsEditor.OnInspectorGUI
  fullName: Repetitionless.Editor.Samples.TerrainSceneSettingsEditor.OnInspectorGUI
