### YamlMime:ManagedReference
items:
- uid: Repetitionless.Editor.Config
  commentId: N:Repetitionless.Editor.Config
  id: Repetitionless.Editor.Config
  children:
  - Repetitionless.Editor.Config.RepetitionlessPackageInfo
  langs:
  - csharp
  - vb
  name: Repetitionless.Editor.Config
  nameWithType: Repetitionless.Editor.Config
  fullName: Repetitionless.Editor.Config
  type: Namespace
  assemblies:
  - com.williamschack.Repetitionless.Editor
references:
- uid: Repetitionless.Editor.Config.RepetitionlessPackageInfo
  commentId: T:Repetitionless.Editor.Config.RepetitionlessPackageInfo
  name: RepetitionlessPackageInfo
  nameWithType: RepetitionlessPackageInfo
  fullName: Repetitionless.Editor.Config.RepetitionlessPackageInfo
