### YamlMime:ManagedReference
items:
- uid: Repetitionless.Runtime.Samples.TerrainSceneSettings
  commentId: T:Repetitionless.Runtime.Samples.TerrainSceneSettings
  id: TerrainSceneSettings
  parent: Repetitionless.Runtime.Samples
  children:
  - Repetitionless.Runtime.Samples.TerrainSceneSettings.SelectRepetitionlessMaterial
  - Repetitionless.Runtime.Samples.TerrainSceneSettings.TerrainUsingRepetitionless
  - Repetitionless.Runtime.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless
  - Repetitionless.Runtime.Samples.TerrainSceneSettings.UpdateRepetitionlessTerrainMaterial
  langs:
  - csharp
  - vb
  name: TerrainSceneSettings
  nameWithType: TerrainSceneSettings
  fullName: Repetitionless.Runtime.Samples.TerrainSceneSettings
  type: Class
  source:
    remote:
      path: True Seamless Texturing/Assets/Samples/Repetitionless/1.0.0/Core Sample Assets/Scripts/Runtime/TerrainSceneSettings.cs
      branch: main
      repo: https://github.com/WilliamSchack/True-Seamless-Texturing.git
    id: TerrainSceneSettings
    path: ../../True Seamless Texturing/Assets/Samples/Repetitionless/1.0.0/Core Sample Assets/Scripts/Runtime/TerrainSceneSettings.cs
    startLine: 8
  assemblies:
  - com.williamschack.Repetitionless.Runtime.Samples
  namespace: Repetitionless.Runtime.Samples
  syntax:
    content: 'public class TerrainSceneSettings : MonoBehaviour'
    content.vb: Public Class TerrainSceneSettings Inherits MonoBehaviour
  inheritance:
  - System.Object
  - UnityEngine.Object
  - UnityEngine.Component
  - UnityEngine.Behaviour
  - UnityEngine.MonoBehaviour
- uid: Repetitionless.Runtime.Samples.TerrainSceneSettings.TerrainUsingRepetitionless
  commentId: F:Repetitionless.Runtime.Samples.TerrainSceneSettings.TerrainUsingRepetitionless
  id: TerrainUsingRepetitionless
  parent: Repetitionless.Runtime.Samples.TerrainSceneSettings
  langs:
  - csharp
  - vb
  name: TerrainUsingRepetitionless
  nameWithType: TerrainSceneSettings.TerrainUsingRepetitionless
  fullName: Repetitionless.Runtime.Samples.TerrainSceneSettings.TerrainUsingRepetitionless
  type: Field
  source:
    remote:
      path: True Seamless Texturing/Assets/Samples/Repetitionless/1.0.0/Core Sample Assets/Scripts/Runtime/TerrainSceneSettings.cs
      branch: main
      repo: https://github.com/WilliamSchack/True-Seamless-Texturing.git
    id: TerrainUsingRepetitionless
    path: ../../True Seamless Texturing/Assets/Samples/Repetitionless/1.0.0/Core Sample Assets/Scripts/Runtime/TerrainSceneSettings.cs
    startLine: 17
  assemblies:
  - com.williamschack.Repetitionless.Runtime.Samples
  namespace: Repetitionless.Runtime.Samples
  syntax:
    content: >-
      [HideInInspector]

      public bool TerrainUsingRepetitionless
    return:
      type: System.Boolean
    content.vb: >-
      <HideInInspector>

      Public TerrainUsingRepetitionless As Boolean
  attributes:
  - type: UnityEngine.HideInInspector
    ctor: UnityEngine.HideInInspector.#ctor
    arguments: []
- uid: Repetitionless.Runtime.Samples.TerrainSceneSettings.UpdateRepetitionlessTerrainMaterial
  commentId: M:Repetitionless.Runtime.Samples.TerrainSceneSettings.UpdateRepetitionlessTerrainMaterial
  id: UpdateRepetitionlessTerrainMaterial
  parent: Repetitionless.Runtime.Samples.TerrainSceneSettings
  langs:
  - csharp
  - vb
  name: UpdateRepetitionlessTerrainMaterial()
  nameWithType: TerrainSceneSettings.UpdateRepetitionlessTerrainMaterial()
  fullName: Repetitionless.Runtime.Samples.TerrainSceneSettings.UpdateRepetitionlessTerrainMaterial()
  type: Method
  source:
    remote:
      path: True Seamless Texturing/Assets/Samples/Repetitionless/1.0.0/Core Sample Assets/Scripts/Runtime/TerrainSceneSettings.cs
      branch: main
      repo: https://github.com/WilliamSchack/True-Seamless-Texturing.git
    id: UpdateRepetitionlessTerrainMaterial
    path: ../../True Seamless Texturing/Assets/Samples/Repetitionless/1.0.0/Core Sample Assets/Scripts/Runtime/TerrainSceneSettings.cs
    startLine: 19
  assemblies:
  - com.williamschack.Repetitionless.Runtime.Samples
  namespace: Repetitionless.Runtime.Samples
  syntax:
    content: public void UpdateRepetitionlessTerrainMaterial()
    content.vb: Public Sub UpdateRepetitionlessTerrainMaterial()
  overload: Repetitionless.Runtime.Samples.TerrainSceneSettings.UpdateRepetitionlessTerrainMaterial*
- uid: Repetitionless.Runtime.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless
  commentId: M:Repetitionless.Runtime.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless
  id: ToggleTerrainRepetitionless
  parent: Repetitionless.Runtime.Samples.TerrainSceneSettings
  langs:
  - csharp
  - vb
  name: ToggleTerrainRepetitionless()
  nameWithType: TerrainSceneSettings.ToggleTerrainRepetitionless()
  fullName: Repetitionless.Runtime.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless()
  type: Method
  source:
    remote:
      path: True Seamless Texturing/Assets/Samples/Repetitionless/1.0.0/Core Sample Assets/Scripts/Runtime/TerrainSceneSettings.cs
      branch: main
      repo: https://github.com/WilliamSchack/True-Seamless-Texturing.git
    id: ToggleTerrainRepetitionless
    path: ../../True Seamless Texturing/Assets/Samples/Repetitionless/1.0.0/Core Sample Assets/Scripts/Runtime/TerrainSceneSettings.cs
    startLine: 39
  assemblies:
  - com.williamschack.Repetitionless.Runtime.Samples
  namespace: Repetitionless.Runtime.Samples
  syntax:
    content: public void ToggleTerrainRepetitionless()
    content.vb: Public Sub ToggleTerrainRepetitionless()
  overload: Repetitionless.Runtime.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless*
- uid: Repetitionless.Runtime.Samples.TerrainSceneSettings.SelectRepetitionlessMaterial
  commentId: M:Repetitionless.Runtime.Samples.TerrainSceneSettings.SelectRepetitionlessMaterial
  id: SelectRepetitionlessMaterial
  parent: Repetitionless.Runtime.Samples.TerrainSceneSettings
  langs:
  - csharp
  - vb
  name: SelectRepetitionlessMaterial()
  nameWithType: TerrainSceneSettings.SelectRepetitionlessMaterial()
  fullName: Repetitionless.Runtime.Samples.TerrainSceneSettings.SelectRepetitionlessMaterial()
  type: Method
  source:
    remote:
      path: True Seamless Texturing/Assets/Samples/Repetitionless/1.0.0/Core Sample Assets/Scripts/Runtime/TerrainSceneSettings.cs
      branch: main
      repo: https://github.com/WilliamSchack/True-Seamless-Texturing.git
    id: SelectRepetitionlessMaterial
    path: ../../True Seamless Texturing/Assets/Samples/Repetitionless/1.0.0/Core Sample Assets/Scripts/Runtime/TerrainSceneSettings.cs
    startLine: 65
  assemblies:
  - com.williamschack.Repetitionless.Runtime.Samples
  namespace: Repetitionless.Runtime.Samples
  syntax:
    content: public void SelectRepetitionlessMaterial()
    content.vb: Public Sub SelectRepetitionlessMaterial()
  overload: Repetitionless.Runtime.Samples.TerrainSceneSettings.SelectRepetitionlessMaterial*
references:
- uid: Repetitionless.Runtime.Samples
  commentId: N:Repetitionless.Runtime.Samples
  name: Repetitionless.Runtime.Samples
  nameWithType: Repetitionless.Runtime.Samples
  fullName: Repetitionless.Runtime.Samples
  spec.csharp:
  - uid: Repetitionless
    name: Repetitionless
  - name: .
  - uid: Repetitionless.Runtime
    name: Runtime
  - name: .
  - uid: Repetitionless.Runtime.Samples
    name: Samples
  spec.vb:
  - uid: Repetitionless
    name: Repetitionless
  - name: .
  - uid: Repetitionless.Runtime
    name: Runtime
  - name: .
  - uid: Repetitionless.Runtime.Samples
    name: Samples
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: UnityEngine.Object
  commentId: T:UnityEngine.Object
  parent: UnityEngine
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: UnityEngine.Object
- uid: UnityEngine.Component
  commentId: T:UnityEngine.Component
  parent: UnityEngine
  isExternal: true
  name: Component
  nameWithType: Component
  fullName: UnityEngine.Component
- uid: UnityEngine.Behaviour
  commentId: T:UnityEngine.Behaviour
  parent: UnityEngine
  isExternal: true
  name: Behaviour
  nameWithType: Behaviour
  fullName: UnityEngine.Behaviour
- uid: UnityEngine.MonoBehaviour
  commentId: T:UnityEngine.MonoBehaviour
  parent: UnityEngine
  isExternal: true
  name: MonoBehaviour
  nameWithType: MonoBehaviour
  fullName: UnityEngine.MonoBehaviour
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Repetitionless.Runtime.Samples.TerrainSceneSettings.UpdateRepetitionlessTerrainMaterial*
  commentId: Overload:Repetitionless.Runtime.Samples.TerrainSceneSettings.UpdateRepetitionlessTerrainMaterial
  name: UpdateRepetitionlessTerrainMaterial
  nameWithType: TerrainSceneSettings.UpdateRepetitionlessTerrainMaterial
  fullName: Repetitionless.Runtime.Samples.TerrainSceneSettings.UpdateRepetitionlessTerrainMaterial
- uid: Repetitionless.Runtime.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless*
  commentId: Overload:Repetitionless.Runtime.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless
  name: ToggleTerrainRepetitionless
  nameWithType: TerrainSceneSettings.ToggleTerrainRepetitionless
  fullName: Repetitionless.Runtime.Samples.TerrainSceneSettings.ToggleTerrainRepetitionless
- uid: Repetitionless.Runtime.Samples.TerrainSceneSettings.SelectRepetitionlessMaterial*
  commentId: Overload:Repetitionless.Runtime.Samples.TerrainSceneSettings.SelectRepetitionlessMaterial
  name: SelectRepetitionlessMaterial
  nameWithType: TerrainSceneSettings.SelectRepetitionlessMaterial
  fullName: Repetitionless.Runtime.Samples.TerrainSceneSettings.SelectRepetitionlessMaterial
