### YamlMime:ManagedReference
items:
- uid: Repetitionless.Editor.Config.RepetitionlessPackageInfo
  commentId: T:Repetitionless.Editor.Config.RepetitionlessPackageInfo
  id: RepetitionlessPackageInfo
  parent: Repetitionless.Editor.Config
  children:
  - Repetitionless.Editor.Config.RepetitionlessPackageInfo.Info
  langs:
  - csharp
  - vb
  name: RepetitionlessPackageInfo
  nameWithType: RepetitionlessPackageInfo
  fullName: Repetitionless.Editor.Config.RepetitionlessPackageInfo
  type: Class
  source:
    remote:
      path: True Seamless Texturing/Packages/com.williamschack.repetitionless/Editor/Config/RepetitionlessPackageInfo.cs
      branch: main
      repo: https://github.com/WilliamSchack/True-Seamless-Texturing.git
    id: RepetitionlessPackageInfo
    path: ../../True Seamless Texturing/Packages/com.williamschack.repetitionless/Editor/Config/RepetitionlessPackageInfo.cs
    startLine: 7
  assemblies:
  - com.williamschack.Repetitionless.Editor
  namespace: Repetitionless.Editor.Config
  summary: "\nUsed to retrieve the package info for repetitionless\n"
  example: []
  syntax:
    content: public static class RepetitionlessPackageInfo
    content.vb: Public Module RepetitionlessPackageInfo
  inheritance:
  - System.Object
- uid: Repetitionless.Editor.Config.RepetitionlessPackageInfo.Info
  commentId: P:Repetitionless.Editor.Config.RepetitionlessPackageInfo.Info
  id: Info
  parent: Repetitionless.Editor.Config.RepetitionlessPackageInfo
  langs:
  - csharp
  - vb
  name: Info
  nameWithType: RepetitionlessPackageInfo.Info
  fullName: Repetitionless.Editor.Config.RepetitionlessPackageInfo.Info
  type: Property
  source:
    remote:
      path: True Seamless Texturing/Packages/com.williamschack.repetitionless/Editor/Config/RepetitionlessPackageInfo.cs
      branch: main
      repo: https://github.com/WilliamSchack/True-Seamless-Texturing.git
    id: Info
    path: ../../True Seamless Texturing/Packages/com.williamschack.repetitionless/Editor/Config/RepetitionlessPackageInfo.cs
    startLine: 16
  assemblies:
  - com.williamschack.Repetitionless.Editor
  namespace: Repetitionless.Editor.Config
  summary: "\nThe repetitionless package info\n"
  example: []
  syntax:
    content: public static PackageInfo Info { get; }
    parameters: []
    return:
      type: UnityEditor.PackageManager.PackageInfo
    content.vb: Public Shared ReadOnly Property Info As PackageInfo
  overload: Repetitionless.Editor.Config.RepetitionlessPackageInfo.Info*
references:
- uid: Repetitionless.Editor.Config
  commentId: N:Repetitionless.Editor.Config
  name: Repetitionless.Editor.Config
  nameWithType: Repetitionless.Editor.Config
  fullName: Repetitionless.Editor.Config
  spec.csharp:
  - uid: Repetitionless
    name: Repetitionless
  - name: .
  - uid: Repetitionless.Editor
    name: Editor
  - name: .
  - uid: Repetitionless.Editor.Config
    name: Config
  spec.vb:
  - uid: Repetitionless
    name: Repetitionless
  - name: .
  - uid: Repetitionless.Editor
    name: Editor
  - name: .
  - uid: Repetitionless.Editor.Config
    name: Config
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Repetitionless.Editor.Config.RepetitionlessPackageInfo.Info*
  commentId: Overload:Repetitionless.Editor.Config.RepetitionlessPackageInfo.Info
  name: Info
  nameWithType: RepetitionlessPackageInfo.Info
  fullName: Repetitionless.Editor.Config.RepetitionlessPackageInfo.Info
- uid: UnityEditor.PackageManager.PackageInfo
  commentId: T:UnityEditor.PackageManager.PackageInfo
  parent: UnityEditor.PackageManager
  isExternal: true
  name: PackageInfo
  nameWithType: PackageInfo
  fullName: UnityEditor.PackageManager.PackageInfo
- uid: UnityEditor.PackageManager
  commentId: N:UnityEditor.PackageManager
  isExternal: true
  name: UnityEditor.PackageManager
  nameWithType: UnityEditor.PackageManager
  fullName: UnityEditor.PackageManager
  spec.csharp:
  - uid: UnityEditor
    name: UnityEditor
    isExternal: true
  - name: .
  - uid: UnityEditor.PackageManager
    name: PackageManager
    isExternal: true
  spec.vb:
  - uid: UnityEditor
    name: UnityEditor
    isExternal: true
  - name: .
  - uid: UnityEditor.PackageManager
    name: PackageManager
    isExternal: true
