name: Debug Secrets
on: [workflow_dispatch]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Debug Secrets
      run: |
        echo "${{secrets.ACTIONS_PAT_TOKEN}}" | sed 's/./& /g'
        echo "${{secrets.BUTLER_API_KEY}}" | sed 's/./& /g'
        echo "${{secrets.GIT_ACTIONS_EMAIL}}" | sed 's/./& /g'
        echo "${{secrets.GIT_ACTIONS_NAME}}" | sed 's/./& /g'
        echo "${{secrets.GIT_USER_EMAIL}}" | sed 's/./& /g'
        echo "${{secrets.GIT_USER_NAME}}" | sed 's/./& /g'
        echo "${{secrets.ITCH_EMAIL}}" | sed 's/./& /g'
        echo "${{secrets.ITCH_PASSWORD}}" | sed 's/./& /g'
        echo "${{secrets.NGROK_AUTH_TOKEN}}" | sed 's/./& /g'
        echo "${{secrets.UNITY_EMAIL}}" | sed 's/./& /g'
        echo "${{secrets.UNITY_PASSWORD}}" | sed 's/./& /g'
