name: Setup New Release

on:
  workflow_dispatch:
    inputs:
      release_notes_updated:
        description: 'Have you updated the release notes?'
        default: false
        required: true
        type: boolean
      version:
        description: 'Version tag (no leading "v")'
        default: ''
        required: true
        type: string

permissions:
  contents: write

jobs:
  validation:
    name: Validating Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Validating Inputs
        if: ${{ github.event.inputs.release_notes_updated != 'true' }}
        run: exit 1

  # update_files_and_build:
  #   name: Updating Files and Building Package
  #   runs-on: ubuntu-22.04
  #   needs: validation
  #   strategy:
  #     matrix:
  #       project-path: [ ReleaseNotes.md ]
  #   steps:
  #     - name: Free Up Storage
  #       uses: jlumbroso/free-disk-space@main
  #       with:
  #         android: false
  #         dotnet: true
  #         haskell: true
  #         large-packages: false
  #         docker-images: false
  #         swap-storage: false
  #     - uses: actions/checkout@v4
  #       with:
  #         sparse-checkout:  ${{ matrix.project-path }}
  #     - name: Install mkdocs
  #       working-directory: "Documentation"
  #       run: |
  #         pip install --upgrade pip
  #         pip install -r requirements.txt
  #     - name: Build Docs
  #       working-directory: "Documentation"
  #       run: |
  #         mkdocs build
  #     - name: Move offline docs
  #       run: |
  #         mv "Documentation/site/pdf/document.pdf" "${{ matrix.project-path }}/Packages/com.williamschack.repetitionless/OfflineDocumentation.pdf"
  #         rmdir "Documentation/site/pdf"
  #     - name: Write new version to package.json
  #       working-directory: "${{ matrix.project-path }}/Packages/com.williamschack.repetitionless"
  #       run: |
  #         jq '.version = "${{ github.event.inputs.version }}"' package.json > package.tmp
  #         mv package.tmp package.json
  #     - name: Push changes
  #       run: |
  #         git config --global user.name '${{ secrets.GIT_USER_NAME }}'
  #         git config --global user.email '${{ secrets.GIT_USER_EMAIL }}'
  #         git add -A
  #         git commit -m '[automated commit] v${{ inputs.version }} Updated docs and package.json'
  #         git push
  #     - name: Cache Library
  #       uses: actions/cache@v3
  #       with:
  #         path: "${{ matrix.project-path }}/Library"
  #         key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
  #         restore-keys: |
  #           Library-
  #     - name: Install Unity
  #       uses: buildalon/unity-setup@v2
  #       id: unity-setup
  #       with:
  #         version-file: '${{ matrix.project-path }}/ProjectSettings/ProjectVersion.txt'
  #         cache-installation: true
  #     - name: Activate Unity
  #       uses: buildalon/activate-unity-license@v2
  #       with:
  #         license: 'Personal'
  #         username: ${{ secrets.UNITY_EMAIL }}
  #         password: ${{ secrets.UNITY_PASSWORD }}
  #     - name: Export and Upload Package
  #       env:
  #         UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  #         UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  #         PACKAGE_VERSION: ${{ github.event.inputs.version }}
  #       run: |
  #         "${{ steps.unity-setup.outputs.unity-editor-path }}" \
  #         -projectPath "${{ steps.unity-setup.outputs.unity-project-path }}" \
  #         -batchmode \
  #         -nographics \
  #         -executeMethod AutoPackageMaker.CreateAndUpload \
  #         -stackTraceLogType None \
  #         -logFile -
  #     - name: Upload Package Artifact
  #       uses: actions/upload-artifact@v6
  #       with:
  #         name: repetitionless-package
  #         path: ${{ env.PACKAGE_PATH }}

  # create_release:
  #   name: Create Github Release
  #   runs-on: ubuntu-latest
  #   needs: update_files_and_build
  #   strategy:
  #     matrix:
  #       package-download-dir: [ "/package" ]
  #       release-notes-filename: [ "ReleaseSetup/ReleaseNotes.md" ]
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         sparse-checkout: ${{ matrix.release-notes-filename }}
  #     - name: Make Directory For Package
  #       run: |
  #         mkdir ${{ matrix.package-download-dir }}
  #     - name: Download Package
  #       uses: actions/download-artifact@v6
  #       with:
  #         name: repetitionless-package
  #         path: ${{ matrix.package-download-dir }}
  #     - name: Find Package
  #       run: |
  #         FILE=$(find ${{ matrix.package-download-dir }} -type f -name "*.unitypackage" | head -n 1)
  #         echo "PACKAGE_PATH=$FILE" >> $GITHUB_ENV
  #     - name: Get Release Notes
  #       id: release-notes
  #       run: |
  #         echo "release-notes=$(cat ${{ matrix.release-notes-filename }})" >> $GITHUB_OUTPUT
  #     - name: Create Github Release
  #       uses: softprops/action-gh-release@v2.5.0
  #       with:
  #         tag_name: v${{ github.event.inputs.version }}
  #         body_path: ${{ matrix.release-notes-filename }}
  #         files: ${{ env.PACKAGE_PATH }}

  unity_publish:
    name: Publish Unity Package Draft
    runs-on: ubuntu-latest
    needs: validation
    strategy:
      matrix:
        package-download-dir: [ "/package" ]
        release-setup-folder: [ "ReleaseSetup" ]
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ matrix.release-setup-folder }}
      - name: Get Unity Publisher API
        uses: actions/checkout@v4
        with:
          repository: WilliamSchack/UnityPublisherAPI
          token: ${{ secrets.ACTIONS_PAT_TOKEN }}
          path: ${{ matrix.release-setup-folder }}
      - uses: actions/setup-python@v6
      - name: Install md2html
        run: |
          npm install -g markdown
      - run: ls ${{ matrix.release-setup-folder }}
      - name: Convert release notes to html
        run: |
          cd ${{ matrix.release-setup-folder }}
          md2html ${{ matrix.release-setup-folder }}/ReleaseNotes.md > ${{ matrix.release-setup-folder }}/ReleaseNotes.html
      - name: Update Unity Package
        run: |
          cd ${{ matrix.release-setup-folder }}
          python ${{ matrix.release-setup-folder }}/ReleaseUnity.py  ${{ secrets.UNITY_EMAIL }} ${{ secrets.UNITY_PASSWORD }} ${{ github.event.inputs.version }} ReleaseNotes.html

  # cleanup:
  #   name: Cleanup
  #   runs-on: ubuntu-latest
  #   needs: [ create_release, unity_publish]
  #   steps:
  #   - name: Remove Artifacts
  #     uses: geekyeggo/delete-artifact@v5
  #     with:
  #       name: repetitionless-package
