# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      release_notes_updated:
        description: 'Have you updated the release notes?'
        default: false
        required: true
        type: boolean
      version:
        description: 'Version tag (no leading "v")'
        default: ''
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Validating Inputs
        if: ${{ github.event.inputs.release_notes_updated != 'true' }}
        run: exit 1

  update_package_info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Write new version
        working-directory: "True Seamless Texturing/Packages/com.williamschack.repetitionless"
        run: jq '.version = "${{ github.event.inputs.version }}"' package.json
        

  #test_package:
 #  needs: [ validation, update_package_info ]
 # 
 #   runs-on: ubuntu-latest
 #   steps:
 #     - name: Testing 2023.3.26f1
